"""runhistory table

Revision ID: 3ddcdb067cb7
Revises: cb03ca06d398
Create Date: 2019-03-12 17:48:37.909267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ddcdb067cb7'
down_revision = 'cb03ca06d398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('time_started', sa.DateTime(), nullable=True),
    sa.Column('time_completed', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('logfile', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runhistory_user'), 'runhistory', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runhistory_user'), table_name='runhistory')
    op.drop_table('runhistory')
    # ### end Alembic commands ###
