"""apiusers table

Revision ID: cb03ca06d398
Revises: 9de4c2eee8e8
Create Date: 2019-03-01 22:22:52.972160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb03ca06d398'
down_revision = '9de4c2eee8e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adminusers_username'), 'adminusers', ['username'], unique=True)
    op.create_table('apiusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('notify', sa.Boolean(), nullable=False),
    sa.Column('ldap_user', sa.String(length=64), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apiusers_email'), 'apiusers', ['email'], unique=False)
    op.create_index(op.f('ix_apiusers_username'), 'apiusers', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apiusers_username'), table_name='apiusers')
    op.drop_index(op.f('ix_apiusers_email'), table_name='apiusers')
    op.drop_table('apiusers')
    op.drop_index(op.f('ix_adminusers_username'), table_name='adminusers')
    op.drop_table('adminusers')
    # ### end Alembic commands ###
